language: node_js
notifications:
  email:
    on_success: never
    on_failure: change
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
branches:
  only:
  - master
  - "/^v?[0-9\\.]+/"
node_js:
- '8'
- '9'
- '10'
script:
- npm run test
